/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PrintName */

#ifndef _Included_PrintName
#define _Included_PrintName
/*
 * Class:     PrintName
 * Method:    printName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_PrintName_printName
  (JNIEnv *, jclass, jstring);

#endif
